# Generated by Django 2.1.3 on 2018-11-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='state',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='state',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
