# Generated by Django 2.1.3 on 2018-11-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_trip_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='otp',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
