# Generated by Django 2.1.3 on 2018-11-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_driver_numberoftrips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
