# Generated by Django 2.1.3 on 2018-11-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181118_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='lastLocation',
            field=models.CharField(choices=[('ap', 'Airport'), ('ba', 'Baguiati'), ('lt', 'Lake Town'), ('bg', 'Beleghata'), ('rh', 'Ruby Hospital')], default='bg', max_length=100, null=True),
        ),
    ]
